server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost/stock
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

appDescription: "stock API"
appVersion: "1.0.0"